version: "3.9"  

services:
  rod:
    image: ghcr.io/go-rod/rod
    ports:
      - "7317:7317"
    expose:
      - "7317"
    volumes:
      - ./db-data:/data
#    network_mode: "host"
  db:
    image: postgres
    restart: always
    user: postgres
#    secrets:
#      - db-data-password
#    volumes:
#      - ./db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=real-estate
      - POSTGRES_PASSWORD=123456
#      - POSTGRES_PASSWORD_FILE=/run/secrets/db-data-password
    expose:
      - 5432
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
#    network_mode: "host"

  redis:
    image: redislabs/redismod
    ports:
      - '6379:6379'
#    network_mode: "host"

  real-estate:
    container_name: real-estate
    build: .
    #    volumes:
    #      - ./db-data:./
    ports:
      - "8080:8080"
    expose:
      - 8080
#    network_mode: "host"

