// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0

package estate

import (
	"time"

	"github.com/google/uuid"
)

type Estate struct {
	ID         uuid.UUID
	IDEstate   string
	Urlstr     string
	Addressstr string
	Surface    float64
	RoomAmount string
	PricePerM2 float64
	Price      float64
	Query      string
	City       string
	OfferDate  time.Time
	RentPrice  float64
}
