// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0

package estate

import (
	"github.com/google/uuid"
)

type Estate struct {
	ID         uuid.UUID
	Urlstr     string
	Addressstr string
	Surface    string
	RoomAmount string
	PricePerM2 string
	Price      string
	Query      string
}
